language: node_js
node_js:
- 6.9.4
sudo: false
install: npm --production=false install
script:
  - npm run build
  - npm run build-examples
before_deploy: "cd build && pwd"
deploy:
  provider: script
  script: pwd
  skip_cleanup: true