language: node_js
node_js:
- 6.9.4
sudo: false
install: npm --production=false install
script:
  - npm run build
  - npm run build-examples
deploy:
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  on:
    tags: true